lib/jit_disasm.c: fix build
Fix the following build failure raised since
http://git.savannah.gnu.org/cgit/lightning.git/commit/?id=837c7a1e8d08fb9294578dc84694077f4d6106f9:

jit_disasm.c: In function 'fprintf_styled':
jit_disasm.c:57:27: error: parameter name omitted
   57 | static int fprintf_styled(void *, enum disassembler_style, const char* fmt, ...)
      |                           ^~~~~~
jit_disasm.c:57:35: error: parameter name omitted
   57 | static int fprintf_styled(void *, enum disassembler_style, const char* fmt, ...)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/e15e01e98e0d8c873efd3f512b671d98e4daf6c0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>